---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: workload
    app.kubernetes.io/instance: diamond
    app.kubernetes.io/name: diamond
    app.kubernetes.io/version: dev
  name: diamond
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: workload
      app.kubernetes.io/instance: diamond
      app.kubernetes.io/name: diamond
  template:
    metadata:
      labels:
        app.kubernetes.io/component: workload
        app.kubernetes.io/instance: diamond
        app.kubernetes.io/name: diamond
        app.kubernetes.io/version: dev
    spec:
      containers:
      - name: diamond
        ports:
        - containerPort: 8080
          name: http
        args:
          - /bin/diamond
          - --address=:8080
          - --log-level=info
        image: localhost:5000/diamond:dev
        livenessProbe:
          httpGet:
            host: localhost
            path: /live
            port: 8080
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            host: localhost
            path: /ready
            port: 8080
          initialDelaySeconds: 10
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
      serviceAccountName: diamond
      terminationGracePeriodSeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: workload
    app.kubernetes.io/instance: diamond
    app.kubernetes.io/name: diamond
  name: default
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: workload
    app.kubernetes.io/instance: diamond
    app.kubernetes.io/name: diamond
